# Generated by Django 4.2.7 on 2024-08-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(choices=[('rear', 'Задний'), ('front', 'Передний'), ('full', 'Полный')], default='rear', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electro', 'Электро')], default='gasoline', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('вариатор', 'CVT'), ('robot', 'Робот')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
