# Generated by Django 4.2.7 on 2024-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_color_car_drive_unit_car_fuel_type_car_gearbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ManyToManyField(to='main.car'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ManyToManyField(to='main.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
