# Generated by Django 4.2.7 on 2024-08-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sale_car_sale_client_sale_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='car',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
